name: it2-fuzzy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.25.2
  - scipy>=1.11
  - pandas>=2.0
  - scikit-learn=1.3.0
  - matplotlib>=3.7
  - pytest>=7.4
  - pip
